db_type: none
server_limit: 100
port: 19132
bindip: 0.0.0.0
kick_inactive: true
custom_servers: server.json
user_servers: false
featured_servers: false
#whitelist: whitelist.txt
fetch_ips: true
language: zh_CN.json
debug: false
#motd: motd.txt
motd_first_join: true
motd_cooldown: 0
store_display_names: true
#packet_limit: 200
#global_packet_limit: 100000
