name: Auto fetch

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Update submodule
      run: |
        cd BedrockConnect
        git fetch
        latest_tag=$(curl https://api.github.com/repos/Pugmatt/BedrockConnect/releases/latest 2>/dev/null | jq .tag_name -r)
        now_tag=$(git tag --points-at HEAD)
        echo latest_tag=${latest_tag} now_tag=${now_tag}
        [ "$latest_tag" == "$now_tag" ] && exit 0
        echo Start update BedrockConnect.
        echo Before the update.
        git show HEAD --shortstat
        git reset --hard $(git show-ref ${latest_tag} | awk '{print $1}')
        echo After the update.
        git show HEAD --shortstat
        cd ..
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-update at $(date)"
        echo Auto update info.
        git show HEAD --shortstat
        git push
