name: Auto fetch

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Update submodule
      run: |
        set -x
        cd BedrockConnect
        git fetch
        latest_tag=$(curl https://api.github.com/repos/Pugmatt/BedrockConnect/releases/latest 2>/dev/null | jq .tag_name -r)
        latest_commit=$(curl https://api.github.com/repos/Pugmatt/BedrockConnect/git/ref/tags/${latest_tag} | jq .object.sha -r)
        now_commit=$(git rev-parse HEAD)
        echo latest_commit=${latest_commit} now_commit=${now_commit}
        [ "$latest_commit" == "$now_commit" ] && exit 0
        echo Start update BedrockConnect.
        echo Before the update.
        git show HEAD --shortstat
        git reset --hard ${latest_commit}
        echo After the update.
        git show HEAD --shortstat
        cd ..
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto-update at $(date)"
        echo Auto update info.
        git show HEAD --shortstat
        git push
